version: '3.8'
name: 'OCW Social glitch-soc upgrade'
services:
  upgrade:
    image: smallsonlinemstdncontainers.azurecr.io/ocwsocial-glitch-soc:latest
    restart: "no"
    env_file: .env.production
    environment:
      - SKIP_POST_DEPLOYMENT_MIGRATIONS=true
    command: bash -c "bundle exec rails db:migrate"
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system

networks:
  external_network:
  internal_network:
    internal: true
